project:
  type: book
  output-dir: "_book"

book:
  title: "Australian Mining"
  subtitle: "Production output, prices, and value 1922-2021"
  author: "Daniel Moul"
  date: now
  chapters: 
    - index.qmd
    - yearly-output.qmd
    - yearly-prices.qmd
    - yearly-value.qmd
    - notes.qmd

format:
  html:
    code-fold: true
    number-sections: true
    code-summary: "Show the code"
    page-layout: full
    toc: true
    toc-depth: 3
    title-block-banner: true  
